language: c


env:
  global:
    - RACKET_DIR=~/racket

before_install:
  - bash ./.install-racket.sh
  - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us

install:

before_script:
 - raco pkg install --deps search-auto sicp

script:
  - raco test --heartbeat --table .

